site: KiRa-KiRa Sensation
url: https://vmmoe.com
title: KiRa-KiRa Sensation
description: KiRa-KiRa Sensation

permalink: pretty

paginate:            10
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
  - scope:
      path: "assets/images"
    values:
      image: true
